% This method is called from loadErrTable.m. There is no need to run this
% separately. Workspace data needed for the plot is generated by
% loadErrTable.m
figure
scat_out_RF = zeros(7,3);
scat_out_GB = zeros(7,3);
scat_out_AB = zeros(7,3);
i = 1;
for wln_ = [15 25 35]
    A = tb_err(find(tb_err.wln == wln_), [7]);
    scat_out_RF(:,i) = A.MAbsErr(:,1);
    scat_out_GB(:,i) = A.MAbsErr(:,2);
    scat_out_AB(:,i) = A.MAbsErr(:,3);
    i = i+1;
end

% Create a formatted heatmap
imagesc([scat_out_GB])
colorbar
xticks(1:9)
xticklabels({'15','25','35','15','25','35','15','25','35'})
yticks(1:7)
yticklabels({'5','7','9','11','13','15','17'})
xlabel('Window Length')
ylabel('Number of Samples')
set(gca,'FontSize',28,'FontName','TimesNewRoman')